name: Publish to npm
on: workflow_dispatch
inputs:
  npmTag:
    description: 'npm tag to publishing to (Use either `latest` or `next`)'
    required: false
    default: 'next'
  npmVersion:
    description: 'package version to publish to npm'
    required: false
    default: 'prerelease'

jobs:
  compile-binaries:
    # TODO: main
    uses: temporalio/sdk-typescript/.github/workflows/compile-binaries.yml@auto-publish
    with:
      publishPackages: false

  publish:
    runs-on: ubuntu-latest
    needs: compile-binaries
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: actions/download-artifact@v2
        with:
          path: ${{ github.workspace }}/packages/core-bridge/releases

      - run: ls -l ./packages/core-bridge/releases
